INSERT INTO categoria VALUES (5725, 1, 'Accesorios para Vehículos');
INSERT INTO categoria VALUES (5725, 2, 'Accesorios para Vehículos');
INSERT INTO categoria VALUES (5725, 3, 'Accesorios para Vehículos');
INSERT INTO categoria VALUES (5725, 4, 'Accesorios para Vehículos');
INSERT INTO categoria VALUES (5725, 5, 'Accesorios para Vehículos');
INSERT INTO categoria VALUES (1403, 1, 'Alimentos y Bebidas');
INSERT INTO categoria VALUES (1403, 2, 'Alimentos y Bebidas');
INSERT INTO categoria VALUES (1403, 3, 'Alimentos y Bebidas');
INSERT INTO categoria VALUES (1403, 4, 'Alimentos y Bebidas');
INSERT INTO categoria VALUES (1403, 5, 'Alimentos y Bebidas');
INSERT INTO categoria VALUES (1071, 1, 'Animales y Mascotas');
INSERT INTO categoria VALUES (1071, 2, 'Animales y Mascotas');
INSERT INTO categoria VALUES (1071, 3, 'Animales y Mascotas');
INSERT INTO categoria VALUES (1071, 4, 'Animales y Mascotas');
INSERT INTO categoria VALUES (1071, 5, 'Animales y Mascotas');
INSERT INTO categoria VALUES (1367, 1, 'Antigüedades');
INSERT INTO categoria VALUES (1367, 2, 'Antigüedades');
INSERT INTO categoria VALUES (1367, 3, 'Antigüedades');
INSERT INTO categoria VALUES (1367, 4, 'Antigüedades');
INSERT INTO categoria VALUES (1367, 5, 'Antigüedades');
INSERT INTO categoria VALUES (1368, 1, 'Arte y Artesanías');
INSERT INTO categoria VALUES (1368, 2, 'Arte y Artesanías');
INSERT INTO categoria VALUES (1368, 3, 'Arte y Artesanías');
INSERT INTO categoria VALUES (1368, 4, 'Arte y Artesanías');
INSERT INTO categoria VALUES (1368, 5, 'Arte y Artesanías');
INSERT INTO categoria VALUES (1743, 1, 'Autos, Motos y Otros');
INSERT INTO categoria VALUES (1743, 2, 'Autos, Motos y Otros');
INSERT INTO categoria VALUES (1743, 3, 'Autos, Motos y Otros');
INSERT INTO categoria VALUES (1743, 4, 'Autos, Motos y Otros');
INSERT INTO categoria VALUES (1743, 5, 'Autos, Motos y Otros');
INSERT INTO categoria VALUES (1384, 1, 'Bebés');
INSERT INTO categoria VALUES (1384, 2, 'Bebés');
INSERT INTO categoria VALUES (1384, 3, 'Bebés');
INSERT INTO categoria VALUES (1384, 4, 'Bebés');
INSERT INTO categoria VALUES (1384, 5, 'Bebés');
INSERT INTO categoria VALUES (1246, 1, 'Belleza y Cuidado Personal');
INSERT INTO categoria VALUES (1246, 2, 'Belleza y Cuidado Personal');
INSERT INTO categoria VALUES (1246, 3, 'Belleza y Cuidado Personal');
INSERT INTO categoria VALUES (1246, 4, 'Belleza y Cuidado Personal');
INSERT INTO categoria VALUES (1246, 5, 'Belleza y Cuidado Personal');
INSERT INTO categoria VALUES (1039, 1, 'Cámaras y Accesorios');
INSERT INTO categoria VALUES (1039, 2, 'Cámaras y Accesorios');
INSERT INTO categoria VALUES (1039, 3, 'Cámaras y Accesorios');
INSERT INTO categoria VALUES (1039, 4, 'Cámaras y Accesorios');
INSERT INTO categoria VALUES (1039, 5, 'Cámaras y Accesorios');
INSERT INTO categoria VALUES (1051, 1, 'Celulares y Teléfonos');
INSERT INTO categoria VALUES (1051, 2, 'Celulares y Teléfonos');
INSERT INTO categoria VALUES (1051, 3, 'Celulares y Teléfonos');
INSERT INTO categoria VALUES (1051, 4, 'Celulares y Teléfonos');
INSERT INTO categoria VALUES (1051, 5, 'Celulares y Teléfonos');
INSERT INTO categoria VALUES (1798, 1, 'Coleccionables y Hobbies');
INSERT INTO categoria VALUES (1798, 2, 'Coleccionables y Hobbies');
INSERT INTO categoria VALUES (1798, 3, 'Coleccionables y Hobbies');
INSERT INTO categoria VALUES (1798, 4, 'Coleccionables y Hobbies');
INSERT INTO categoria VALUES (1798, 5, 'Coleccionables y Hobbies');
INSERT INTO categoria VALUES (1648, 1, 'Computación');
INSERT INTO categoria VALUES (1648, 2, 'Computación');
INSERT INTO categoria VALUES (1648, 3, 'Computación');
INSERT INTO categoria VALUES (1648, 4, 'Computación');
INSERT INTO categoria VALUES (1648, 5, 'Computación');
INSERT INTO categoria VALUES (1144, 1, 'Consolas y Videojuegos');
INSERT INTO categoria VALUES (1144, 2, 'Consolas y Videojuegos');
INSERT INTO categoria VALUES (1144, 3, 'Consolas y Videojuegos');
INSERT INTO categoria VALUES (1144, 4, 'Consolas y Videojuegos');
INSERT INTO categoria VALUES (1144, 5, 'Consolas y Videojuegos');
INSERT INTO categoria VALUES (1276, 1, 'Deportes y Fitness');
INSERT INTO categoria VALUES (1276, 2, 'Deportes y Fitness');
INSERT INTO categoria VALUES (1276, 3, 'Deportes y Fitness');
INSERT INTO categoria VALUES (1276, 4, 'Deportes y Fitness');
INSERT INTO categoria VALUES (1276, 5, 'Deportes y Fitness');
INSERT INTO categoria VALUES (5726, 1, 'Electrodomésticos y Aires Ac.');
INSERT INTO categoria VALUES (5726, 2, 'Electrodomésticos y Aires Ac.');
INSERT INTO categoria VALUES (5726, 3, 'Electrodomésticos y Aires Ac.');
INSERT INTO categoria VALUES (5726, 4, 'Electrodomésticos y Aires Ac.');
INSERT INTO categoria VALUES (5726, 5, 'Electrodomésticos y Aires Ac.');
INSERT INTO categoria VALUES (1000, 1, 'Electrónica, Audio y Video');
INSERT INTO categoria VALUES (1000, 2, 'Electrónica, Audio y Video');
INSERT INTO categoria VALUES (1000, 3, 'Electrónica, Audio y Video');
INSERT INTO categoria VALUES (1000, 4, 'Electrónica, Audio y Video');
INSERT INTO categoria VALUES (1000, 5, 'Electrónica, Audio y Video');
INSERT INTO categoria VALUES (2547, 1, 'Entradas para Eventos');
INSERT INTO categoria VALUES (2547, 2, 'Entradas para Eventos');
INSERT INTO categoria VALUES (2547, 3, 'Entradas para Eventos');
INSERT INTO categoria VALUES (2547, 4, 'Entradas para Eventos');
INSERT INTO categoria VALUES (2547, 5, 'Entradas para Eventos');
INSERT INTO categoria VALUES (407134, 1, 'Herramientas y Construcción');
INSERT INTO categoria VALUES (407134, 2, 'Herramientas y Construcción');
INSERT INTO categoria VALUES (407134, 3, 'Herramientas y Construcción');
INSERT INTO categoria VALUES (407134, 4, 'Herramientas y Construcción');
INSERT INTO categoria VALUES (407134, 5, 'Herramientas y Construcción');
INSERT INTO categoria VALUES (1574, 1, 'Hogar, Muebles y Jardín');
INSERT INTO categoria VALUES (1574, 2, 'Hogar, Muebles y Jardín');
INSERT INTO categoria VALUES (1574, 3, 'Hogar, Muebles y Jardín');
INSERT INTO categoria VALUES (1574, 4, 'Hogar, Muebles y Jardín');
INSERT INTO categoria VALUES (1574, 5, 'Hogar, Muebles y Jardín');
INSERT INTO categoria VALUES (1499, 1, 'Industrias y Oficinas');
INSERT INTO categoria VALUES (1499, 2, 'Industrias y Oficinas');
INSERT INTO categoria VALUES (1499, 3, 'Industrias y Oficinas');
INSERT INTO categoria VALUES (1499, 4, 'Industrias y Oficinas');
INSERT INTO categoria VALUES (1499, 5, 'Industrias y Oficinas');
INSERT INTO categoria VALUES (1459, 1, 'Inmuebles');
INSERT INTO categoria VALUES (1459, 2, 'Inmuebles');
INSERT INTO categoria VALUES (1459, 3, 'Inmuebles');
INSERT INTO categoria VALUES (1459, 4, 'Inmuebles');
INSERT INTO categoria VALUES (1459, 5, 'Inmuebles');
INSERT INTO categoria VALUES (1182, 1, 'Instrumentos Musicales');
INSERT INTO categoria VALUES (1182, 2, 'Instrumentos Musicales');
INSERT INTO categoria VALUES (1182, 3, 'Instrumentos Musicales');
INSERT INTO categoria VALUES (1182, 4, 'Instrumentos Musicales');
INSERT INTO categoria VALUES (1182, 5, 'Instrumentos Musicales');
INSERT INTO categoria VALUES (3937, 1, 'Joyas y Relojes');
INSERT INTO categoria VALUES (3937, 2, 'Joyas y Relojes');
INSERT INTO categoria VALUES (3937, 3, 'Joyas y Relojes');
INSERT INTO categoria VALUES (3937, 4, 'Joyas y Relojes');
INSERT INTO categoria VALUES (3937, 5, 'Joyas y Relojes');
INSERT INTO categoria VALUES (1132, 1, 'Juegos y Juguetes');
INSERT INTO categoria VALUES (1132, 2, 'Juegos y Juguetes');
INSERT INTO categoria VALUES (1132, 3, 'Juegos y Juguetes');
INSERT INTO categoria VALUES (1132, 4, 'Juegos y Juguetes');
INSERT INTO categoria VALUES (1132, 5, 'Juegos y Juguetes');
INSERT INTO categoria VALUES (3025, 1, 'Libros, Revistas y Comics');
INSERT INTO categoria VALUES (3025, 2, 'Libros, Revistas y Comics');
INSERT INTO categoria VALUES (3025, 3, 'Libros, Revistas y Comics');
INSERT INTO categoria VALUES (3025, 4, 'Libros, Revistas y Comics');
INSERT INTO categoria VALUES (3025, 5, 'Libros, Revistas y Comics');
INSERT INTO categoria VALUES (1168, 1, 'Música, Películas y Series');
INSERT INTO categoria VALUES (1168, 2, 'Música, Películas y Series');
INSERT INTO categoria VALUES (1168, 3, 'Música, Películas y Series');
INSERT INTO categoria VALUES (1168, 4, 'Música, Películas y Series');
INSERT INTO categoria VALUES (1168, 5, 'Música, Películas y Series');
INSERT INTO categoria VALUES (1430, 1, 'Ropa y Accesorios');
INSERT INTO categoria VALUES (1430, 2, 'Ropa y Accesorios');
INSERT INTO categoria VALUES (1430, 3, 'Ropa y Accesorios');
INSERT INTO categoria VALUES (1430, 4, 'Ropa y Accesorios');
INSERT INTO categoria VALUES (1430, 5, 'Ropa y Accesorios');
INSERT INTO categoria VALUES (409431, 1, 'Salud y Equipamiento Médico');
INSERT INTO categoria VALUES (409431, 2, 'Salud y Equipamiento Médico');
INSERT INTO categoria VALUES (409431, 3, 'Salud y Equipamiento Médico');
INSERT INTO categoria VALUES (409431, 4, 'Salud y Equipamiento Médico');
INSERT INTO categoria VALUES (409431, 5, 'Salud y Equipamiento Médico');
INSERT INTO categoria VALUES (1540, 1, 'Servicios');
INSERT INTO categoria VALUES (1540, 2, 'Servicios');
INSERT INTO categoria VALUES (1540, 3, 'Servicios');
INSERT INTO categoria VALUES (1540, 4, 'Servicios');
INSERT INTO categoria VALUES (1540, 5, 'Servicios');
INSERT INTO categoria VALUES (1953, 1, 'Otras categorías');
INSERT INTO categoria VALUES (1953, 2, 'Otras categorías');
INSERT INTO categoria VALUES (1953, 3, 'Otras categorías');
INSERT INTO categoria VALUES (1953, 4, 'Otras categorías');
INSERT INTO categoria VALUES (1953, 5, 'Otras categorías');
