INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (1,'Guy Hurst',2,'8373 Quisque St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (2,'Evan Andrews',1,'P.O. Box 973, 2041 Arcu Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (3,'Mannix Burks',2,'868 Pellentesque. St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (4,'Brittany Reyes',2,'P.O. Box 630, 5949 Nunc. Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (5,'Mira Bradshaw',4,'Ap #659-5965 Adipiscing Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (6,'Serena Poole',4,'P.O. Box 728, 4265 Molestie Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (7,'Lester Winters',0,'6360 Libero. St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (8,'Shad Joyner',1,'Ap #819-5395 Fusce Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (9,'Paloma Rosario',3,'Ap #881-3785 Pellentesque Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (10,'Harlan Bailey',4,'155-4048 Pretium Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (11,'Ashely Haney',4,'5432 Libero Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (12,'Holmes Watkins',1,'P.O. Box 495, 3934 Felis St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (13,'Delilah Ashley',3,'131-7229 Nam Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (14,'Stephanie Meyer',1,'P.O. Box 462, 5414 Ad Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (15,'Signe Chandler',3,'6339 Metus. St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (16,'Casey Lyons',1,'Ap #448-5909 Eget Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (17,'Kiona Tate',1,'P.O. Box 992, 4827 Ac, Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (18,'Kaden Ramos',3,'474-2744 Libero. Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (19,'Elaine Bernard',4,'8586 Dapibus Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (20,'Vladimir Ballard',1,'Ap #845-1718 Morbi Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (21,'Xandra Camacho',1,'9570 Neque. St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (22,'Alisa Cummings',3,'854-8264 Congue. Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (23,'Chloe Goodwin',1,'Ap #362-195 Ligula Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (24,'Kendall Decker',0,'497-9256 Orci, Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (25,'Elvis Allison',0,'375-4220 Dictum Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (26,'Sacha Mack',0,'Ap #989-7214 Tellus Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (27,'Kato Hendrix',1,'Ap #237-8508 Tristique Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (28,'Daria Baird',3,'530-8836 Egestas Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (29,'Duncan Mendez',1,'Ap #102-2705 Eget Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (30,'Alexandra Durham',4,'618-2036 Euismod Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (31,'Brett Velez',1,'P.O. Box 834, 3589 Sed St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (32,'Maya Forbes',3,'P.O. Box 775, 4968 Arcu. Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (33,'Aidan Mays',2,'986-7201 Penatibus Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (34,'Alexander Chambers',2,'488-5410 Eget Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (35,'Gage Mcfadden',1,'Ap #405-3353 Nec Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (36,'Walker Delaney',0,'P.O. Box 148, 8576 Est St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (37,'Calvin Avery',1,'Ap #800-8325 Mollis Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (38,'Marvin Kirkland',2,'P.O. Box 128, 1704 Mauris, Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (39,'Brennan Pierce',0,'P.O. Box 887, 9210 Dolor. Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (40,'Clark Britt',3,'P.O. Box 381, 8596 Suscipit St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (41,'Phillip Castaneda',2,'8316 Nec Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (42,'Alma Rose',2,'Ap #335-1203 Neque Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (43,'Elizabeth Fernandez',1,'218-8802 Parturient St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (44,'Lydia Hahn',2,'1423 Ipsum St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (45,'Rama Mayer',2,'522 Ligula Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (46,'Clare Kirby',4,'Ap #396-5215 Vestibulum Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (47,'Damian Scott',0,'P.O. Box 364, 5635 Nec, Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (48,'Joel Robertson',2,'Ap #764-8020 Sapien. Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (49,'Carl Roberts',1,'590-3089 Curabitur Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (50,'Hollee Osborne',2,'Ap #360-2327 Sociis Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (51,'Hasad Reeves',1,'7828 Odio Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (52,'Megan Brock',0,'478 Erat, Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (53,'Honorato Cooke',2,'8846 Pharetra Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (54,'Wing Fry',4,'P.O. Box 699, 2154 Proin Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (55,'Wanda Blake',3,'Ap #381-788 Sit St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (56,'Ferdinand Patton',4,'3884 Lorem, Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (57,'Zenia Young',3,'7804 Lobortis Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (58,'Mohammad Macias',4,'Ap #973-4601 Rhoncus. Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (59,'Shelly Casey',4,'P.O. Box 886, 5506 Posuere, Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (60,'Maggie Hull',3,'P.O. Box 769, 8352 Velit. Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (61,'Cameron Bolton',0,'P.O. Box 205, 6429 Cum Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (62,'Mari Lawson',1,'Ap #220-4506 Dolor. Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (63,'Alec Harrington',3,'P.O. Box 958, 1696 Amet, Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (64,'Ifeoma Warren',0,'9744 Nunc Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (65,'Olga Chambers',2,'6405 Libero St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (66,'Marny Mayer',1,'P.O. Box 483, 4494 Egestas Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (67,'Hedwig Wood',2,'208-8308 Felis St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (68,'Eden Albert',1,'Ap #893-6539 Malesuada Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (69,'Vladimir Cannon',4,'9392 Cras Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (70,'Alden Campos',3,'970-659 Nulla Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (71,'Judah Pena',0,'Ap #842-8510 Est Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (72,'Devin Rutledge',0,'P.O. Box 294, 7259 Adipiscing Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (73,'Cairo Gordon',1,'2689 Libero. Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (74,'Moana Case',3,'296-3657 Enim. St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (75,'Kiona Cook',2,'5053 Etiam Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (76,'Kylan Rios',2,'P.O. Box 441, 2282 Donec Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (77,'Kyla Lindsay',2,'Ap #380-8554 Porttitor Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (78,'Aristotle Richard',4,'Ap #146-7117 Egestas Road');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (79,'Kevin Conley',2,'646 Neque. Av.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (80,'Xenos Avila',1,'559-1965 Proin St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (81,'Victoria Shaffer',2,'5473 Amet, Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (82,'Giacomo Hickman',3,'Ap #594-9647 Vitae Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (83,'Demetria Alford',3,'P.O. Box 503, 525 Non Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (84,'Dieter Weber',3,'2956 Nunc Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (85,'Brandon Mason',2,'P.O. Box 993, 7554 Leo Avenue');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (86,'Jolene Walker',2,'P.O. Box 514, 1658 Mollis St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (87,'Germaine Byers',3,'2935 Nibh. St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (88,'Diana Bradshaw',1,'P.O. Box 951, 4359 Dui. Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (89,'Jade Cunningham',2,'758-4740 Neque St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (90,'Eve Donovan',4,'790-4824 Suspendisse Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (91,'Giacomo Klein',1,'616 Duis Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (92,'Shannon Moody',0,'P.O. Box 556, 2931 Dolor St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (93,'Ian Barber',3,'5173 Varius. St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (94,'Rhonda Joseph',3,'331-132 Leo. Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (95,'Gemma Sandoval',0,'Ap #146-7641 Et, Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (96,'Wynter Duncan',2,'Ap #196-6907 Nulla Rd.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (97,'Drew Fulton',2,'1618 Placerat. Street');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (98,'Sara Cooley',4,'P.O. Box 759, 774 Donec Ave');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (99,'Francesca Haney',0,'3365 Nunc St.');
INSERT INTO "cliente" (cod_cliente,nombre,cod_tipo,direccion) VALUES (100,'Tamekah Cooper',0,'Ap #431-4596 Aliquet. Rd.');
