INSERT INTO categoria VALUES (5725, 'Accesorios para Vehículos');
INSERT INTO categoria VALUES (1403, 'Alimentos y Bebidas');
INSERT INTO categoria VALUES (1071, 'Animales y Mascotas');
INSERT INTO categoria VALUES (1367, 'Antigüedades');
INSERT INTO categoria VALUES (1368, 'Arte y Artesanías');
INSERT INTO categoria VALUES (1743, 'Autos, Motos y Otros');
INSERT INTO categoria VALUES (1384, 'Bebés');
INSERT INTO categoria VALUES (1246, 'Belleza y Cuidado Personal');
INSERT INTO categoria VALUES (1039, 'Cámaras y Accesorios');
INSERT INTO categoria VALUES (1051, 'Celulares y Teléfonos');
INSERT INTO categoria VALUES (1798, 'Coleccionables y Hobbies');
INSERT INTO categoria VALUES (1648, 'Computación');
INSERT INTO categoria VALUES (1144, 'Consolas y Videojuegos');
INSERT INTO categoria VALUES (1276, 'Deportes y Fitness');
INSERT INTO categoria VALUES (5726, 'Electrodomésticos y Aires Ac.');
INSERT INTO categoria VALUES (1000, 'Electrónica, Audio y Video');
INSERT INTO categoria VALUES (2547, 'Entradas para Eventos');
INSERT INTO categoria VALUES (407134, 'Herramientas y Construcción');
INSERT INTO categoria VALUES (1574, 'Hogar, Muebles y Jardín');
INSERT INTO categoria VALUES (1499, 'Industrias y Oficinas');
INSERT INTO categoria VALUES (1459, 'Inmuebles');
INSERT INTO categoria VALUES (1182, 'Instrumentos Musicales');
INSERT INTO categoria VALUES (3937, 'Joyas y Relojes');
INSERT INTO categoria VALUES (1132, 'Juegos y Juguetes');
INSERT INTO categoria VALUES (3025, 'Libros, Revistas y Comics');
INSERT INTO categoria VALUES (1168, 'Música, Películas y Series');
INSERT INTO categoria VALUES (1430, 'Ropa y Accesorios');
INSERT INTO categoria VALUES (409431, 'Salud y Equipamiento Médico');
INSERT INTO categoria VALUES (1540, 'Servicios');
INSERT INTO categoria VALUES (1953, 'Otras categorías');
