-- Script de carga generado con http://www.generatedata.com/
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2600,'Benedict Hardy',2,'P.O. Box 988, 3940 Faucibus Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6741,'Deanna Roth',10,'P.O. Box 891, 5600 Et Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2278,'Tamekah Barr',7,'P.O. Box 415, 1471 Proin Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6215,'Martena Mckee',9,'P.O. Box 166, 2911 Feugiat St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2125,'Xenos Farmer',5,'P.O. Box 690, 921 Magnis Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4622,'Kelly Ingram',10,'P.O. Box 906, 236 Metus. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5760,'Odysseus Arnold',7,'Ap #314-6645 Eget Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4147,'Lucy Henry',1,'Ap #351-8076 Est St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7907,'Octavius Ray',1,'P.O. Box 862, 8708 Eu, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7603,'Levi English',10,'222 Purus Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (667,'Tyrone Fox',4,'338-1769 Suspendisse Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9994,'Cally Garza',6,'P.O. Box 539, 6415 Vestibulum Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8884,'Lane Knight',5,'Ap #790-9118 Ultrices. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5744,'Ryder Simmons',7,'Ap #296-1485 Malesuada Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1075,'Olympia Berger',2,'P.O. Box 136, 9099 Litora St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2949,'Leroy Fischer',9,'731-4911 Non Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4760,'Garth Mccarthy',5,'Ap #516-3587 Volutpat Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5921,'Yardley Huber',4,'930-3209 Enim, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1164,'Daquan Atkinson',10,'737 Diam St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7556,'Whitney Fields',9,'396-2416 Pede Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (596,'Ella Acevedo',6,'267-4108 Ut Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4145,'Gwendolyn Tyson',6,'596-526 Malesuada Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2571,'Barry Lang',9,'P.O. Box 777, 8443 Integer Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6469,'Maggie Roth',8,'5095 Convallis Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2988,'Melyssa Barron',5,'187 Risus. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1335,'Camden Wood',2,'Ap #819-3519 Arcu. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (772,'Eliana Logan',5,'Ap #374-1891 Hendrerit. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5603,'Carolyn Gentry',4,'P.O. Box 518, 7711 Et Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4725,'Daniel Richmond',5,'773-9105 Eget Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9512,'Yoshi Mack',8,'993-8257 Suspendisse St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6254,'Kane Ayers',3,'P.O. Box 961, 6044 Curabitur Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4118,'Linda Acosta',1,'4689 Adipiscing Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (804,'Shelley Rivas',8,'Ap #180-2646 Felis. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1443,'Kim Delacruz',2,'Ap #360-1575 Nec, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6672,'Amy Britt',3,'P.O. Box 281, 6726 Quis, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5561,'Kevyn Huff',5,'3798 Placerat St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (936,'Elvis Mendez',3,'Ap #254-7000 Lobortis Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7133,'Keiko Garcia',2,'P.O. Box 909, 2711 Urna. Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9228,'Owen Carver',8,'117-8140 Convallis Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1551,'Virginia Mcintyre',10,'5556 Enim Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6989,'Ali Gaines',9,'102-6129 Nunc Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5439,'Brenna Reynolds',4,'841-4042 Dapibus St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5253,'Chloe Hammond',9,'5176 Tempor, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7687,'Nerea Sellers',4,'Ap #202-9929 Sit Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3946,'Oleg Mitchell',5,'495-3025 Eget, Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9238,'Raja Fernandez',5,'601-4080 Quis, Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4963,'Aline Hughes',9,'1767 Nisi Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6225,'Pascale Lynn',6,'Ap #412-3285 Non, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4472,'Ginger Bryant',6,'Ap #173-1694 Quam, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7012,'Vanna Jordan',5,'4339 Curabitur Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9578,'Theodore Norman',9,'505-2498 Montes, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (637,'April Randolph',4,'Ap #587-1568 Semper St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5676,'Lillian Cleveland',5,'4275 Egestas, Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4086,'Sawyer Mays',8,'3825 Lectus St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3431,'Gregory Weaver',1,'Ap #861-3754 Sapien, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6075,'Chaim Bradford',4,'185 Montes, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (752,'Uma Bolton',9,'7080 Eget Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7139,'Griffith Grimes',7,'7182 Dolor. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1760,'Amena Horne',2,'406 Nostra, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4522,'Knox Cunningham',3,'881-5668 Donec Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5340,'Rinah Kane',4,'172-5241 Eu Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2335,'Jordan Valenzuela',9,'Ap #375-9844 Adipiscing Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6106,'Jeremy Salazar',10,'Ap #972-7547 Vehicula Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9930,'Martena Nunez',8,'Ap #539-3209 Lectus Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4387,'Gareth Flores',1,'8141 Lobortis Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7913,'Yen Walters',1,'Ap #144-4294 At Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5215,'Ocean Crosby',8,'2681 At, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3304,'Suki Perez',1,'976-2839 Tempor St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4914,'Merrill Mooney',9,'286-7033 Ut Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (832,'Shaine Koch',8,'8087 Integer Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5907,'Boris Arnold',2,'6079 Felis Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4820,'Deanna Ford',6,'6522 Volutpat. Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8345,'Zeph Guzman',10,'745-3262 Felis. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (571,'Nelle Velazquez',8,'P.O. Box 450, 9219 Metus Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8441,'Amena Glenn',2,'929-4776 Sem. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (225,'Rina Best',7,'6003 Integer Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5145,'Janna Doyle',9,'7076 Ultrices. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3516,'Sonia Roth',1,'Ap #328-9449 Velit Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7082,'Whoopi Kirk',9,'116-8637 Lectus. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2303,'Basil Cash',1,'268-5493 Massa. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3160,'Grant Morse',2,'P.O. Box 215, 8685 Gravida. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8833,'Irene Wolf',5,'4244 Odio, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6387,'Rebekah Acevedo',10,'P.O. Box 675, 1846 Vel Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6452,'Driscoll Jones',8,'4896 Commodo St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9127,'Ainsley Beasley',9,'200-6400 Ultricies Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2546,'Fuller English',5,'Ap #420-4452 Arcu. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3709,'Brynne Good',5,'8780 Cursus Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8231,'Jorden Valentine',9,'8618 A St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3654,'Iliana Howe',3,'P.O. Box 778, 7557 A, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8273,'Anjolie Dixon',6,'920-1206 Mi, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5143,'Kelly Neal',6,'Ap #789-3572 Nibh. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7189,'Julie Wade',9,'649-8621 Sit Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2011,'Libby Rose',6,'896 Convallis Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8891,'Maxwell Howe',10,'Ap #228-9511 Erat Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7867,'Serina White',3,'8571 Mauris Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (349,'Chancellor Lara',10,'712-9918 Ut St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8505,'Brenna Mullen',7,'Ap #800-392 Donec Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1945,'Jillian Reyes',5,'818 Ornare. Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (359,'Rhoda Beasley',4,'P.O. Box 609, 1007 Mattis. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7822,'Lana Potts',8,'732-7626 Ullamcorper Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (711,'Vaughan Mcfarland',5,'P.O. Box 305, 908 Phasellus Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1096,'Daria Brown',5,'882-396 Et Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (865,'Jaden Vinson',3,'Ap #413-1142 Sapien. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2215,'Isadora Fitzgerald',1,'Ap #557-1365 Auctor, Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1708,'Chiquita Parker',10,'Ap #225-9014 Varius Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6811,'Darryl Trujillo',5,'P.O. Box 164, 4824 Ac Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1263,'Neve Hanson',3,'6924 Quam Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3787,'Georgia Waters',3,'180-937 Dis Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5754,'Shana Morrow',4,'6068 Natoque Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2414,'Lisandra Bernard',4,'Ap #977-7990 Donec St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8290,'Indira Mcdonald',4,'P.O. Box 690, 1688 Tincidunt Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1100,'Martina Foreman',6,'2108 Metus Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7151,'Ria Hancock',2,'Ap #864-8382 Nec, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1917,'Gil Saunders',5,'Ap #519-3013 Nec, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5701,'Bradley Steele',9,'9144 Maecenas Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5933,'Montana Buchanan',7,'P.O. Box 228, 9541 Nec, Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3682,'Frances Williamson',10,'P.O. Box 823, 1394 Dolor Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1574,'Geoffrey Ward',4,'5024 Egestas Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7105,'Jennifer Acosta',6,'P.O. Box 480, 3139 Vestibulum Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6696,'Lacota Hopper',10,'Ap #980-6123 Taciti Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7413,'Kermit Avery',3,'484-4979 Cras Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7521,'Philip Townsend',8,'8339 Sit Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3081,'Isadora Hopkins',10,'Ap #891-2485 Aliquet, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9065,'Eric Mcmillan',5,'1168 Risus. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3621,'Akeem Eaton',10,'556-3515 Adipiscing Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4927,'Myra Hawkins',2,'838-6503 Tincidunt Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5722,'Aladdin Gross',8,'366-8571 Fusce Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4950,'Claire Walker',5,'P.O. Box 989, 4393 Dictum Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9838,'Deborah Delgado',6,'411-674 Orci, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6891,'Stacey Logan',10,'860-3583 Sapien, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (996,'Cade Hyde',9,'P.O. Box 921, 9576 Feugiat Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8323,'Austin Gonzales',3,'Ap #982-2892 Purus Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7284,'Grant Myers',10,'9576 Malesuada Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2234,'Brody Mccarthy',7,'Ap #901-1594 Ornare, Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2634,'Iola Abbott',5,'P.O. Box 224, 4128 Consequat Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4094,'Zelda Rodriquez',5,'223-7676 Netus Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1230,'Emma Herman',10,'3060 Sociis Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1711,'Colette Woodard',9,'226-9533 Dapibus St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6250,'Jason Conrad',9,'9724 Placerat, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9914,'Bo Patton',1,'Ap #326-1612 Sem. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1208,'Xerxes Oliver',3,'P.O. Box 417, 305 Lorem Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9942,'Elliott Le',5,'415-8145 Cras Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8328,'Anika Alvarez',9,'P.O. Box 456, 1391 Enim, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3490,'Melissa Heath',3,'476-6174 Dui, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1126,'Maia Durham',3,'P.O. Box 154, 6923 Lacinia Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8495,'Jamal Gross',5,'Ap #948-8671 Urna. Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8316,'Karleigh Miles',1,'5823 Blandit Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5943,'Abel Case',4,'Ap #664-5481 Enim St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6904,'Fletcher Burns',9,'6567 Elit, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8281,'Noble Roth',3,'P.O. Box 855, 8797 Vehicula. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9251,'Iris Vincent',4,'597-3866 Cursus Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1426,'Erica Gilliam',7,'Ap #911-5098 Aenean Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5562,'Beverly Cannon',3,'Ap #538-6298 Quisque St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3271,'Amos Sims',10,'315-8213 Erat. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6565,'Lev Turner',6,'P.O. Box 877, 9972 Elit. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5788,'Aspen Richards',8,'Ap #108-8680 Quisque Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4485,'Walter Warren',3,'1978 Vitae Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3664,'Germaine Carroll',2,'674-5019 Porttitor St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1412,'Emmanuel Mcclain',6,'2564 Accumsan Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4190,'Beau Gallagher',2,'3036 Tortor. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1271,'Lars Delacruz',4,'P.O. Box 936, 896 A, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (777,'Emerson Ferguson',6,'4034 Vehicula St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5426,'Octavius Mcleod',9,'3393 Nunc. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4779,'Moses Dejesus',6,'Ap #119-2919 Condimentum St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5717,'Sydnee Ramirez',2,'697-6514 Suspendisse St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5302,'Georgia Pate',8,'P.O. Box 363, 9047 Integer St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4254,'Kerry Morse',3,'2097 Enim. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5549,'Scarlet Cunningham',4,'P.O. Box 829, 8363 Bibendum. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (556,'Julian Price',2,'P.O. Box 587, 6954 Amet Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4842,'Melanie Holman',1,'P.O. Box 117, 4469 Ut Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3678,'Ingrid Burton',2,'P.O. Box 686, 2585 Consectetuer, Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3571,'Kimberly Long',1,'Ap #103-3883 In Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3047,'Pearl Brady',8,'Ap #928-6427 Placerat St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6339,'Haviva Cameron',6,'631-8536 Magnis Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5222,'Minerva Hart',10,'482-8363 Et Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9778,'Dylan Terry',10,'Ap #205-3933 Tempor Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1517,'Shaeleigh Martin',5,'Ap #301-2565 Sed Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8764,'Mannix Fisher',8,'P.O. Box 467, 9168 Id Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8496,'Porter Thompson',3,'5292 Feugiat. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6525,'Malachi Burns',3,'P.O. Box 191, 5920 Consectetuer, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4206,'Shelley Wright',9,'346-2434 Aenean St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9163,'Camilla Norton',2,'Ap #628-1286 Orci Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8521,'John Watkins',10,'Ap #312-2624 A, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8538,'Bernard Hardy',4,'317-6163 Aliquam Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9810,'Norman Giles',3,'9335 Nonummy. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2349,'Athena Snow',9,'445-329 In St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9545,'Meredith Griffith',8,'134-9311 Sit Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5347,'Nero Trujillo',2,'286-1169 Sagittis Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6718,'Serena Hatfield',8,'7249 Quis St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (221,'Erica Holloway',7,'787-2437 Aliquam Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4928,'Naomi Witt',5,'772-6061 Non St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8916,'Arthur Hensley',3,'Ap #379-3521 Mauris Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4447,'Lacy Bonner',2,'591-1961 Aenean St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (761,'Chloe Parrish',4,'P.O. Box 855, 9752 Adipiscing Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7604,'Avye Becker',3,'223-4387 Fusce Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9234,'Isabelle Kent',10,'318-9344 A, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (262,'Patrick Ford',8,'P.O. Box 595, 9767 Sit St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2925,'Colton Hunt',2,'163-1580 Urna, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (913,'Eliana Mcmillan',8,'2148 Id St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5629,'Josephine Bartlett',7,'6435 Ut, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9551,'Davis Thornton',2,'456-7123 Vulputate Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3807,'Willa Sanders',10,'563-4178 Sit Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9995,'Hashim Holmes',6,'P.O. Box 876, 5899 Risus. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7759,'Virginia Brennan',5,'Ap #513-7462 Metus. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9783,'Skyler Boone',4,'P.O. Box 543, 1485 Nunc Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6434,'Dakota Donaldson',1,'776-6902 Ut Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8746,'Norman Summers',4,'9373 Felis. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1,'Emma Palmer',1,'747-8151 Pellentesque Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4245,'Tanya Mayer',8,'Ap #489-8708 Vulputate, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9506,'Rose Mendez',9,'P.O. Box 574, 9364 Id Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5035,'Joel Bell',7,'P.O. Box 219, 2745 Libero Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6772,'Mufutau Melton',2,'P.O. Box 457, 9145 Odio St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8358,'Alea York',1,'P.O. Box 383, 6311 Faucibus St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9776,'Micah Rosales',9,'P.O. Box 512, 2530 Neque. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6631,'Melodie Kane',7,'719-1871 Donec Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6086,'James Hill',7,'P.O. Box 490, 5444 Non Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1527,'Remedios Kelly',2,'P.O. Box 620, 8342 Integer St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1053,'Macon Dean',3,'675-9077 Nulla Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6888,'Francis Pickett',4,'1509 Vitae Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7719,'Tatiana Reid',3,'Ap #333-1244 Phasellus Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1964,'Sade Gates',3,'P.O. Box 681, 5810 Arcu. Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5745,'Julian Barnes',5,'1474 Velit Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2965,'April Sutton',1,'2044 Libero. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6212,'Raven Fletcher',4,'P.O. Box 579, 797 Amet, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (346,'Adrienne Brooks',4,'983-1381 Eu Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6123,'Nigel Oneil',9,'Ap #882-8889 Tristique Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1221,'Thane Conrad',6,'737-7327 Rhoncus. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5802,'Perry Green',10,'119-5511 Montes, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3458,'Jeremy Pacheco',10,'Ap #981-121 Est. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7923,'Ray Tillman',1,'340-9329 Et Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7975,'Ebony Mclean',3,'317-4792 Phasellus St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5442,'Uma Lloyd',7,'1626 Blandit Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9448,'Edward Mercado',1,'684-8130 Mauris St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8598,'Caleb Decker',10,'Ap #130-8603 Ornare. Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2585,'Amethyst Monroe',1,'7765 Quisque Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5527,'Shay Mcintyre',4,'5200 Et Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (900,'Davis Hogan',9,'1889 Nunc St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2799,'Janna Schneider',5,'Ap #725-3189 Rhoncus Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4951,'Audrey Peterson',1,'230-2012 Eu, St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1842,'Tatiana Baldwin',5,'9176 Lobortis St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2870,'Leigh Mcmahon',9,'P.O. Box 492, 1862 Massa. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8296,'Abdul Romero',8,'P.O. Box 230, 675 Morbi St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9692,'Linda Sweeney',9,'894-1648 Vestibulum Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (540,'Dieter Hurley',7,'P.O. Box 781, 6168 Sapien. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6028,'Harrison Harmon',3,'303-1247 Tincidunt Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8955,'Lilah Blair',10,'899-8995 Magna St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7143,'Audrey Fowler',9,'P.O. Box 432, 1052 Rutrum St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (204,'Illana Drake',9,'852-3981 Egestas. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5773,'Lillian Holt',6,'P.O. Box 795, 7843 Mauris Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6708,'Guinevere Vega',2,'2387 Donec Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6222,'Iliana Ramsey',7,'Ap #871-8740 Risus, Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6863,'Erasmus Thomas',1,'8948 Dui Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2161,'Kiayada Collier',1,'736-2908 Orci, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3134,'Marshall Ware',4,'7604 Dolor. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3671,'Britanney Anthony',5,'8202 Congue St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5258,'Jakeem Alford',6,'782-5499 Pede, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (753,'Cally Ware',3,'P.O. Box 452, 7306 Mauris, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (133,'Imani Fulton',10,'Ap #385-264 Nulla Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5017,'Caldwell Wyatt',5,'P.O. Box 340, 7732 Donec Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6922,'Kylynn Morse',3,'946-2705 Ante Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7509,'Shay Bean',3,'P.O. Box 593, 2722 Vel, Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (560,'Celeste Young',5,'3904 Suspendisse Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8378,'Drake Washington',8,'P.O. Box 162, 1403 Arcu Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4358,'April Chen',5,'Ap #576-8845 Turpis Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2541,'Kaden Carrillo',8,'9210 Litora Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2653,'Britanni Bishop',10,'P.O. Box 630, 8516 Molestie Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4532,'Rosalyn Randall',9,'3006 Ut Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2452,'Clare Harvey',6,'1076 Aliquam St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7795,'Ethan Dillard',4,'Ap #661-1114 Pede St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2172,'Robert Doyle',9,'5816 Vitae, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6698,'Breanna Nichols',2,'651-7204 Lectus, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7059,'Brian Barr',5,'P.O. Box 938, 6387 Turpis. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9949,'Jescie Sanchez',1,'201-7489 Elit. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6967,'Octavia Barnett',8,'P.O. Box 528, 445 Neque. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (858,'Hanna West',3,'P.O. Box 982, 1994 Massa. Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7834,'Clementine Ferguson',2,'P.O. Box 295, 1228 Scelerisque Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (438,'Nasim Madden',6,'Ap #608-1486 Cum St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4897,'Madonna Campos',2,'P.O. Box 641, 9967 Orci St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5563,'Noble Aguirre',5,'Ap #206-1478 Convallis Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5507,'Zephania Vang',10,'P.O. Box 172, 4384 Bibendum Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1099,'Lacota Duncan',8,'134-2182 Tellus St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9823,'Hector Downs',3,'325-7230 Sem, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (9428,'Talon Eaton',2,'274-9360 Gravida Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (7909,'Dominique Lucas',6,'Ap #168-743 Imperdiet Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6651,'Patrick Kramer',2,'Ap #920-7406 Suspendisse Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6561,'Eliana Torres',4,'2176 Dolor Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1716,'Donna Rodriguez',9,'283-5601 Ultricies Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (3668,'Charity Morrow',8,'P.O. Box 553, 8735 Malesuada Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (6643,'Lareina Good',8,'6383 Metus. Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (5497,'Hop Gay',8,'Ap #547-8910 Praesent Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4851,'Florence Noel',10,'7684 Consequat Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (4754,'Kevyn Lopez',7,'Ap #808-9946 Id Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (265,'Jillian Mason',3,'7935 Fusce Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1200,'Yuri Whitaker',7,'102-4617 Integer Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8747,'Mari Valentine',8,'Ap #799-2900 Eu, Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2311,'Norman Rocha',7,'Ap #645-7650 Ipsum St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (8035,'Brock Wynn',7,'8266 Mollis St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (1646,'Idola Case',5,'Ap #863-1992 Mauris Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (833,'Drew Beach',7,'422-8668 Ac Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (2027,'Jeanette Gaines',7,'117-4345 Risus, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10000,'Guy Hurst',2,'8373 Quisque St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10001,'Evan Andrews',1,'P.O. Box 973, 2041 Arcu Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10002,'Mannix Burks',2,'868 Pellentesque. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10003,'Brittany Reyes',2,'P.O. Box 630, 5949 Nunc. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10004,'Mira Bradshaw',4,'Ap #659-5965 Adipiscing Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10005,'Serena Poole',4,'P.O. Box 728, 4265 Molestie Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10006,'Lester Winters',0,'6360 Libero. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10007,'Shad Joyner',1,'Ap #819-5395 Fusce Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10008,'Paloma Rosario',3,'Ap #881-3785 Pellentesque Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10009,'Harlan Bailey',4,'155-4048 Pretium Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10010,'Ashely Haney',4,'5432 Libero Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10011,'Holmes Watkins',1,'P.O. Box 495, 3934 Felis St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10012,'Delilah Ashley',3,'131-7229 Nam Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10013,'Stephanie Meyer',1,'P.O. Box 462, 5414 Ad Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10014,'Signe Chandler',3,'6339 Metus. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10015,'Casey Lyons',1,'Ap #448-5909 Eget Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10016,'Kiona Tate',1,'P.O. Box 992, 4827 Ac, Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10017,'Kaden Ramos',3,'474-2744 Libero. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10018,'Elaine Bernard',4,'8586 Dapibus Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10019,'Vladimir Ballard',1,'Ap #845-1718 Morbi Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10020,'Xandra Camacho',1,'9570 Neque. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10021,'Alisa Cummings',3,'854-8264 Congue. Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10022,'Chloe Goodwin',1,'Ap #362-195 Ligula Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10023,'Kendall Decker',0,'497-9256 Orci, Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10024,'Elvis Allison',0,'375-4220 Dictum Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10025,'Sacha Mack',0,'Ap #989-7214 Tellus Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10026,'Kato Hendrix',1,'Ap #237-8508 Tristique Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10027,'Daria Baird',3,'530-8836 Egestas Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10028,'Duncan Mendez',1,'Ap #102-2705 Eget Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10029,'Alexandra Durham',4,'618-2036 Euismod Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10030,'Brett Velez',1,'P.O. Box 834, 3589 Sed St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10031,'Maya Forbes',3,'P.O. Box 775, 4968 Arcu. Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10032,'Aidan Mays',2,'986-7201 Penatibus Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10033,'Alexander Chambers',2,'488-5410 Eget Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10034,'Gage Mcfadden',1,'Ap #405-3353 Nec Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10035,'Walker Delaney',0,'P.O. Box 148, 8576 Est St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10036,'Calvin Avery',1,'Ap #800-8325 Mollis Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10037,'Marvin Kirkland',2,'P.O. Box 128, 1704 Mauris, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10038,'Brennan Pierce',0,'P.O. Box 887, 9210 Dolor. Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10039,'Clark Britt',3,'P.O. Box 381, 8596 Suscipit St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10040,'Phillip Castaneda',2,'8316 Nec Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10041,'Alma Rose',2,'Ap #335-1203 Neque Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10042,'Elizabeth Fernandez',1,'218-8802 Parturient St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10043,'Lydia Hahn',2,'1423 Ipsum St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10044,'Rama Mayer',2,'522 Ligula Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10045,'Clare Kirby',4,'Ap #396-5215 Vestibulum Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10046,'Damian Scott',0,'P.O. Box 364, 5635 Nec, Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10047,'Joel Robertson',2,'Ap #764-8020 Sapien. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10048,'Carl Roberts',1,'590-3089 Curabitur Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10049,'Hollee Osborne',2,'Ap #360-2327 Sociis Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10050,'Hasad Reeves',1,'7828 Odio Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10051,'Megan Brock',0,'478 Erat, Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10052,'Honorato Cooke',2,'8846 Pharetra Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10053,'Wing Fry',4,'P.O. Box 699, 2154 Proin Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10054,'Wanda Blake',3,'Ap #381-788 Sit St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10055,'Ferdinand Patton',4,'3884 Lorem, Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10056,'Zenia Young',3,'7804 Lobortis Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10057,'Mohammad Macias',4,'Ap #973-4601 Rhoncus. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10058,'Shelly Casey',4,'P.O. Box 886, 5506 Posuere, Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10059,'Maggie Hull',3,'P.O. Box 769, 8352 Velit. Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10060,'Cameron Bolton',0,'P.O. Box 205, 6429 Cum Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10061,'Mari Lawson',1,'Ap #220-4506 Dolor. Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10062,'Alec Harrington',3,'P.O. Box 958, 1696 Amet, Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10063,'Ifeoma Warren',0,'9744 Nunc Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10064,'Olga Chambers',2,'6405 Libero St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10065,'Marny Mayer',1,'P.O. Box 483, 4494 Egestas Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10066,'Hedwig Wood',2,'208-8308 Felis St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10067,'Eden Albert',1,'Ap #893-6539 Malesuada Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10068,'Vladimir Cannon',4,'9392 Cras Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10069,'Alden Campos',3,'970-659 Nulla Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10070,'Judah Pena',0,'Ap #842-8510 Est Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10071,'Devin Rutledge',0,'P.O. Box 294, 7259 Adipiscing Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10072,'Cairo Gordon',1,'2689 Libero. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10073,'Moana Case',3,'296-3657 Enim. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10074,'Kiona Cook',2,'5053 Etiam Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10075,'Kylan Rios',2,'P.O. Box 441, 2282 Donec Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10076,'Kyla Lindsay',2,'Ap #380-8554 Porttitor Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10077,'Aristotle Richard',4,'Ap #146-7117 Egestas Road');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10078,'Kevin Conley',2,'646 Neque. Av.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10079,'Xenos Avila',1,'559-1965 Proin St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10080,'Victoria Shaffer',2,'5473 Amet, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10081,'Giacomo Hickman',3,'Ap #594-9647 Vitae Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10082,'Demetria Alford',3,'P.O. Box 503, 525 Non Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10083,'Dieter Weber',3,'2956 Nunc Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10084,'Brandon Mason',2,'P.O. Box 993, 7554 Leo Avenue');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10085,'Jolene Walker',2,'P.O. Box 514, 1658 Mollis St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10086,'Germaine Byers',3,'2935 Nibh. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10087,'Diana Bradshaw',1,'P.O. Box 951, 4359 Dui. Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10088,'Jade Cunningham',2,'758-4740 Neque St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10089,'Eve Donovan',4,'790-4824 Suspendisse Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10090,'Giacomo Klein',1,'616 Duis Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10091,'Shannon Moody',0,'P.O. Box 556, 2931 Dolor St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10092,'Ian Barber',3,'5173 Varius. St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10093,'Rhonda Joseph',3,'331-132 Leo. Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10094,'Gemma Sandoval',0,'Ap #146-7641 Et, Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10095,'Wynter Duncan',2,'Ap #196-6907 Nulla Rd.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10096,'Drew Fulton',2,'1618 Placerat. Street');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10097,'Sara Cooley',4,'P.O. Box 759, 774 Donec Ave');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10098,'Francesca Haney',0,'3365 Nunc St.');
INSERT INTO "cliente" (nro_cliente,nombre,tipo,direccion) VALUES (10099,'Tamekah Cooper',0,'Ap #431-4596 Aliquet. Rd.');
